### ISSUE TITLE
Preventing duplication

### ISSUE THREAD

**Issue by rashil2000** [ScoopSearch/ScoopSearch.AzureFunctions#7]
Hi!

I'd like to know how the index is generated. Specifically, what GitHub Search API criteria is used. 

This will help us filter out forks/mirrors of buckets, to prevent any duplication.

For reference, Scoop Directory maintains an [exclusion list](https://github.com/rasa/scoop-directory/blob/master/exclude.txt). 

See also https://github.com/rasa/scoop-directory/issues/39 and https://github.com/rasa/scoop-directory/issues/70

**Comment by gpailler** [comment]
Hello @rashil2000 

The index is generated from multiple sources:
- The official buckets list
- Multiple GitHub search queries (repos with topic `scoop-bucket` and repos containing `scoop-bucket`)
- Some manual buckets

This list is then filtered to exclude some problematic repos.

You can find the list of all the sources/exclusions in [settings.json](https://github.com/ScoopSearch/ScoopSearch.AzureFunctions/blob/main/src/ScoopSearch.Functions/settings.json)

It could be a good idea to use the exclusion list from Scoop Directory as it's way more complete

**Comment by rashil2000** [comment]
I see. Thanks for the detailed info!

**Comment by gpailler** [comment]
@rashil2000 I have integrated the lists include.txt and exclude.txt from rasa/scoop-directory. Could you check if the results are more accurate now (with less duplication)?

btw, do you know if I'm allowed to use the lists from rasa/scoop-directory in the Scoop-Search backend directly?

**Comment by rashil2000** [comment]
> https://github.com/rivy/scoop.bucket.scoop-main

This one, mentioned in https://github.com/rasa/scoop-directory/issues/70#issuecomment-979996314, is still showing up.

> do you know if I'm allowed to use the lists from rasa/scoop-directory in the Scoop-Search backend directly?

The license is compatible, but I think @rasa would be able to answer more clearly.

**Comment by rasa** [comment]
Yes, the MIT license allows you to freely take from [exclude.txt](https://github.com/rasa/scoop-directory/blob/master/exclude.txt). I'm happy we're cross-pollinating. :)

**Comment by gpailler** [comment]
> > [](https://github.com/rivy/scoop.bucket.scoop-main)
> 
> This one, mentioned in [rasa/scoop-directory#70 (comment)](https://github.com/rasa/scoop-directory/issues/70#issuecomment-979996314), is still showing up.

Good catch. This repo is listed in the include.txt and exclude.txt files with a slightly different name. I have created a PR to not include it at all https://github.com/rasa/scoop-directory/pull/80

**Comment by gpailler** [comment]
> Yes, the MIT license allows you to freely take from [exclude.txt](https://github.com/rasa/scoop-directory/blob/master/exclude.txt). I'm happy we're cross-pollinating. :)

Great! I will apply the changes to use the lists directly! 👍

**Comment by gpailler** [comment]
Hey @rasa,
I was integrating the include and exclude lists from rasa-directory and I noticed that `ScoopInstaller/PHP` was added recently to the [exclude.txt](https://github.com/rasa/scoop-directory/blob/f5a3bf04146c86b095a1a0d11075747f9d48f151/exclude.txt#L847) file. (probably during this [GH action run](https://github.com/rasa/scoop-directory/runs/4884951851?check_suite_focus=true#step:5:35))

Do you know if it's an error or if it was done on purpose?

Thanks

**Comment by rasa** [comment]
I think it's an error. I'm gonna turn off auto excluding for now.

**Comment by rasa** [comment]
In fact, there are a ton of false positives in there, so I'm gonna truncate the file for now, and fix this issue later.

**Comment by gpailler** [comment]
Ok thanks for the update and the truncation of exclude.txt.
I just pushed an updated version of the Azure Functions to use the include/exclude files from /rasa/scoop-directory as an additional data source.

Thanks 👍

**Comment by rashil2000** [comment]
Thanks for all the work @rasa and @gpailler🔥

Should I close this issue now?

**Comment by gpailler** [comment]
Please close it 👍

**Comment by rashil2000** [comment]
@gpailler Also, the bucket https://github.com/h404bi/dorado shows up along with https://github.com/chawyehsu/dorado (they're the same, the username of the author changed some time ago). Doesn't ScoopSearch follow redirects?

**Comment by gpailler** [comment]
> Found another recent one: https://github.com/duzyn/wood

This one was excluded recently by rasa (https://github.com/rasa/scoop-directory/commit/6c7c3ba7c16ceb499c1d0b03ecff557a800b6a75#diff-ccf22f3b731e8f66d7cd9259b93200ff0aa6359f690b5d552675dea2babef15e) and is now removed from ScoopSearch database (the ScoopSearch index is updated every 6 hours)

**Comment by gpailler** [comment]
> Also, the bucket https://github.com/h404bi/dorado shows up along with https://github.com/chawyehsu/dorado (they're the same, the username of the author changed some time ago). Doesn't ScoopSearch follow redirects?

Good point. I investigated a bit and noticed the following:
- https://github.com/chawyehsu/dorado is returned by GitHub search 
- https://github.com/h404bi/dorado is returned by [include.txt](https://github.com/rasa/scoop-directory/blob/6c7c3ba7c16ceb499c1d0b03ecff557a800b6a75/include.txt#L32)

On scoop-directory side, it makes sense to update include.txt to use the new URL. 
On ScoopSearch side, I have improved the backend to follow redirections while building the index https://github.com/ScoopSearch/ScoopSearch.AzureFunctions/commit/371bbe5a787904a515028d49149e802a3019ab2a.

With this improvement, I found other buckets redirections:
```
Skipping 'https://github.com/Gladtbam/Scoop_Bucket' because it returns '404' status (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/exclude.txt')
'https://github.com/Kiedtl/open-scoop' redirects to 'https://github.com/lptstr/lptstr-scoop' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/exclude.txt')
'https://github.com/Guard13007/ScoopBucket' redirects to 'https://github.com/TangentFoxy/ScoopBucket' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
'https://github.com/h404bi/dorado' redirects to 'https://github.com/chawyehsu/dorado' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
'https://github.com/lptstr/open-scoop' redirects to 'https://github.com/lptstr/lptstr-scoop' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
'https://github.com/nsstrunks/scoop-bucket' redirects to 'https://github.com/tnessy/scoop-bucket' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
'https://github.com/systemexitzero/scoop-bucket' redirects to 'https://github.com/justsh/scoop-bucket' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
'https://github.com/tapanchandra/scoop-personal' redirects to 'https://github.com/tapannallan/scoop-personal' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
'https://github.com/TnmkFan/my-bucket' redirects to 'https://github.com/DinVolodka/my-bucket' (from 'https://raw.githubusercontent.com/rasa/scoop-directory/master/include.txt')
```

@rashil2000 are you interested in providing a PR on scoop-directory to update include.txt/exlude.txt files?

**Comment by rashil2000** [comment]
See https://github.com/rasa/scoop-directory/pull/83
